// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByAxvAZLW8RyiSyXgHqjRReTUWn5h3IHc',
    appId: '1:764609488893:web:a5e501dd917f27835fdb94',
    messagingSenderId: '764609488893',
    projectId: 'lifthub-a443b',
    authDomain: 'lifthub-a443b.firebaseapp.com',
    storageBucket: 'lifthub-a443b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbATGOguSqSpmUZdssTGJopAxAvO3vQew',
    appId: '1:764609488893:android:cc0f89d4e057dff25fdb94',
    messagingSenderId: '764609488893',
    projectId: 'lifthub-a443b',
    storageBucket: 'lifthub-a443b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfglXwZIx8RD8nyz_CotgYMXrEV5D_W2E',
    appId: '1:764609488893:ios:9c053526030cd0ab5fdb94',
    messagingSenderId: '764609488893',
    projectId: 'lifthub-a443b',
    storageBucket: 'lifthub-a443b.appspot.com',
    iosBundleId: 'com.example.solutionChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfglXwZIx8RD8nyz_CotgYMXrEV5D_W2E',
    appId: '1:764609488893:ios:5564f1dff642a7e65fdb94',
    messagingSenderId: '764609488893',
    projectId: 'lifthub-a443b',
    storageBucket: 'lifthub-a443b.appspot.com',
    iosBundleId: 'com.example.solutionChallenge.RunnerTests',
  );
}
